[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public"]

[db]
port = 54322
major_version = 17

[studio]
port = 54323

[auth]
site_url = "http://localhost:3001"
additional_redirect_urls = ["http://localhost:3001"]
jwt_expiry = 3600

[auth.email]
enable_signup = false
enable_confirmations = false
